os:
  - osx
  - linux

language: c

# needed
sudo: required

compiler:
  - gcc

install:
  - mkdir ezc-dev
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/../ezc-dev
  - make
  - make install
  - cd $PWD/../
  - tar cJf ezc-dev.tar.gz ezc-dev/
  - echo UPLOADING DEV FILE
  - curl --upload-file ./ezc-dev.tar.gz https://transfer.sh/ezc-dev.tar.gz

script:
  -

notifications:
  email:
    recipients:
      - info@chemicaldevelopment.us
    on_success: change
    on_failure: change
