
language: c

install:
  - sudo apt-get install -qq libmpfr-dev
  - make local-noreq

script:
  - make test-local

notifications:
  email:
    recipients:
      - info@chemicaldevelopment.us
    on_success: never # default: change
    on_failure: always # default: always