os:
  - linux
  - osx

language: c

install:
  - sudo make global

script:
  - sudo make check-global

notifications:
  email:
    recipients:
      - info@chemicaldevelopment.us
    on_success: change
    on_failure: change