os:
  - osx
  - linux

language: c

# needed
sudo: required

install:
  - make build
  - make check
  - make bundle
#  - make build

script:
  - make upload
  
#  - make check-global

notifications:
  email:
    recipients:
      - info@chemicaldevelopment.us
    on_success: change
    on_failure: change
