os:
#  - osx
  - linux

language: c

# needed
sudo: required

install:
  - make REQ=false build
# Thanks macOS :(
#  - sudo make global

script:
  - make check
  - make bundle upload
  
#  - make check-global

notifications:
  email:
    recipients:
      - info@chemicaldevelopment.us
    on_success: change
    on_failure: change

deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: ezc-$TRAVIS_OS_NAME.tar.xz
  skip_cleanup: true
  on:
    tags
