os:
  - osx
  - linux

language: c

# needed
sudo: required

compiler:
  - gcc

before_script:
  - sudo add-apt-repository ppa:dns/gnu -y
  - sudo apt-get update -q
  - sudo apt-get install --only-upgrade autoconf

install:
  - autoreconf -i
  - ./configure
  - make clean all
  - sudo make install

notifications:
  email:
    recipients:
      - info@chemicaldevelopment.us
    on_success: change
    on_failure: change
