os:
  - osx
  - linux

language: c

# needed
sudo: required

compiler:
  - gcc

install:
  - ./buildgmp.sh
  - ./buildmpfr.sh
  - ./buildezc.sh
  - mv out/ ezc-dev/
  - tar cJf ezc-dev.tar.gz ezc-dev/
  - echo UPLOADING DEV FILE
  - curl --upload-file ./ezc-dev.tar.gz https://transfer.sh/ezc-dev.tar.gz

script:
  -

notifications:
  email:
    recipients:
      - info@chemicaldevelopment.us
    on_success: change
    on_failure: change
