os:
  - osx
  - linux

language: c

# needed
sudo: required

compiler:
  - gcc

install:
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install

script:
  -

notifications:
  email:
    recipients:
      - info@chemicaldevelopment.us
    on_success: change
    on_failure: change
