
language: c

install:
  - sudo apt-get install -qq libmpfr-dev
  - make global

script:
  - make check-global

notifications:
  email:
    recipients:
      - info@chemicaldevelopment.us
    on_success: change
    on_failure: change