os:
  - linux
  - osx

language: c

install:
  - make local

script:
  - make check-local

notifications:
  email:
    recipients:
      - info@chemicaldevelopment.us
    on_success: change
    on_failure: change