os:
  - osx
  - linux

language: c

# needed
sudo: required

install:
  - make build
# Thanks macOS :(
#  - sudo make global

script:
  - make check
  - make bundle upload
  
#  - make check-global

notifications:
  email:
    recipients:
      - info@chemicaldevelopment.us
    on_success: change
    on_failure: change