os:
  - osx
  - linux

language: c

install:
  - make local
# Thanks macOS :(
#  - sudo make global

script:
  - make check-local
#  - make check-global

notifications:
  email:
    recipients:
      - info@chemicaldevelopment.us
    on_success: change
    on_failure: change