
language: c

install:
  - sudo apt-get install -qq libmpfr-dev
  - make local-noreq

script:
  - make check

notifications:
  email:
    recipients:
      - info@chemicaldevelopment.us
    on_success: change
    on_failure: change