os:
  - osx
  - linux

language: c

# needed
sudo: required

compiler:
  - gcc

install:
  - ./configure
  - make
  - sudo make install

notifications:
  email:
    recipients:
      - info@chemicaldevelopment.us
    on_success: change
    on_failure: change
