os:
  - osx
  - linux

language: c

# needed
sudo: required

compiler:
  - gcc

install:
  - make build
  # this will fail and say the build has cancelled
  #- make check
  #- make bundle package

script:
  #- make upload
  #- make upload-package
  #- make check-global

notifications:
  email:
    recipients:
      - info@chemicaldevelopment.us
    on_success: change
    on_failure: change
